### ISSUE TITLE
xpm list fails with null exception

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#120]
If the package has npm dependencies (which should not be messed!) a failed install leads to exceptions like:

```console
Installed Node.js modules:
error: TypeError: Cannot read properties of null (reading 'name')
    at List.listPackagesFromOneFolder (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/lib/xpm/list.js:369:30)
    at async List.listPackagesLocally (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/lib/xpm/list.js:229:7)
    at async List.doRun (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/lib/xpm/list.js:172:7)
    at async Xpm.main (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:1039:20)
    at async Function.doStart (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:282:22)
    at async Function.start (/home/ilg/.nvm/versions/node/v16.13.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:170:7)
exit(2)
```

**Comment by ilg-ul** [comment]
Fixed on 2021-12-22, with 0.10.9.
