### ISSUE TITLE
Improve error message for missing configuration

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#132]
```console
$ xpm run clean --config native-cmake-clan12-release
error: Error: package.json has no buildConfiguration.native-cmake-clan12-release
    at XpmLiquid.prepareMap (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/node_modules/@xpack/xpm-liquid/dist/lib/xpm-liquid.js:188:27)
    at RunAction.execute (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/lib/xpm/run-action.js:251:36)
    at RunAction.doRun (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/lib/xpm/run-action.js:165:25)
    at async Xpm.main (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:1039:20)
    at async Function.doStart (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:282:22)
    at async Function.start (/home/ilg/.nvm/versions/node/v12.18.1/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:170:7)
```

**Comment by ilg-ul** [comment]
Fixed via #136
