### ISSUE TITLE
Support for any git URL / host

### ISSUE THREAD

**Issue by JoeBenczarski** [xpack/xpm-js#184]
Filing this as a feature request, however this might be a bug. I see there are comments in the install code which seem to intend on any URL being allowed.

I would like to be able to use 'xpm install' for any type of git URL (http/ssh) for any hosting domain (github/gitlab/etc). For my immediate usecase, I have a private git repository hosted on a private GitLab server instance that I would like to use.

npm seems to support this via the following sytax:  git+ssh://git@github.com:xpack/xpm-js.git

It was pretty simple to modify my local xpm source code to enable this. Only two functions needed modification.
    install.js::computeDependencyValue - added a regex to detect a git URL ( the existing URL regex does not match with git ssh links )
    install.js::collectDependency - added a regex to detect a git URL when a URL throws ( i don't fully understand why URL throws, probably due to my privately hosted gitlab server instance )

If this is something that you would like supported, I will make a pull request. Thanks!

**Comment by ilg-ul** [comment]
> npm seems to support this

Generally, xpm uses the same external module to load dependencies as npm, so my expectation is that xpm will accept the same urls as npm.

If you think that the code specific to xpm is limiting this in any way, sure, it must be fixed, and PRs are welcome.

Please be sure that you first check if the urls are accepted by npm.

**Comment by JoeBenczarski** [comment]
> I implemented a new logic, please give it a try and let me know if it works for your use case too.

This works for my usecases. Thanks for adding this!

**Comment by JoeBenczarski** [comment]
Below is the trace for the error...

Identified ^2.13.0 as a dependency.
undefined: No matching version found for undefined@^2.13.0.
    at module.exports (C:\Users\jbenczarski\AppData\Local\Programs\Node\node_modules\xpm\node_modules\npm-pick-manifest\lib\index.js:209:23)
    at RegistryFetcher.manifest (C:\Users\jbenczarski\AppData\Local\Programs\Node\node_modules\xpm\node_modules\pacote\lib\registry.js:119:22)
    at async Install.collectDependency (file:///C:/Users/jbenczarski/AppData/Local/Programs/Node/node_modules/xpm/lib/xpm/install.js:1797:18)
    at async Promise.all (index 2)
    at async Install.collectDependencies (file:///C:/Users/jbenczarski/AppData/Local/Programs/Node/node_modules/xpm/lib/xpm/install.js:1725:7)
    at async Install.collectPackageDependencies (file:///C:/Users/jbenczarski/AppData/Local/Programs/Node/node_modules/xpm/lib/xpm/install.js:1160:5)
    at async Install.installAllDependencies (file:///C:/Users/jbenczarski/AppData/Local/Programs/Node/node_modules/xpm/lib/xpm/install.js:1095:9)
    at async Install.doRun (file:///C:/Users/jbenczarski/AppData/Local/Programs/Node/node_modules/xpm/lib/xpm/install.js:354:7)
    at async Xpm.main (C:\Users\jbenczarski\AppData\Local\Programs\Node\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:1046:20)
    at async Xpm.doStart (C:\Users\jbenczarski\AppData\Local\Programs\Node\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:282:22) {
  code: 'ETARGET',
  type: 'range',
  wanted: '^2.13.0',
  versions: [ '0.1.0' ],
  distTags: { latest: '0.1.0' },
  defaultTag: 'latest'
}
error: Package '^2.13.0' not found
exit(2)

**Comment by ilg-ul** [comment]
sorry, I had a small bug, it must be fixed now.

**Comment by ilg-ul** [comment]
Please also try it with `npm install -g xpm@next`.

**Comment by JoeBenczarski** [comment]
Bug is fixed on my end. I tested it using the xpm@next as you suggested.

**Comment by ilg-ul** [comment]
Thank you, I'll proceed with the public release.

**Comment by ilg-ul** [comment]
Fixed in 0.16.4 on 2023-09-12.
