### ISSUE TITLE
Download of libs not working behind a proxy (HttpsProxyAgent is not a constructor in fetch)

### ISSUE THREAD

**Issue by Sonnenalle** [xpack/xpm-js#207]
## Describe the bug

I tried to download and install the [magickwand.js repoistory](https://github.com/mmomtchev/magickwand.js), but the installation failed with an error message. I am behind a proxy server, so I have set the necessary npm flags, but it doesn't seem to work.
```
$ npm config list | grep proxy
all_proxy = "<ip>:<port>"
http_proxy = "http://<ip>:<port>"
https_proxy = "http://<ip>:<port>"
no_proxy = "<some urls>"
```

## To Reproduce

Steps to reproduce the behaviour:

- be in a network with an HTTP proxy
- configure npm to use said proxy
- clone https://github.com/mmomtchev/magickwand.js
- run npm install

## Expected behaviour

npm install (or better xpm install && xpm run npm-install) should finish successfully (i.e. can download the necessary packages)

## Actual behaviour

install is aborted with an error message:

> HttpsProxyAgent is not a constructor in fetch https://github.com/xpack-dev-tools/cmake-xpack/releases/download/v3.27.9-1/xpack-cmake-3.27.9-1-win32-x64.zip

Trace Log (personal information omitted)
```console
trace: checking 'C:\Users\<omited>\AppData\Roaming\xPacks\@xpack-dev-tools\cmake\3.27.9-1.2.tmp'
trace: expected integrity digest sha256-uBjima1ZInNn4lNEDRoONC1MPBI9ytWJhTHgqarNtWY= for b818e299ad59227367e253440d1a0e342d4c3c123dcad5898531e0a9aacdb566
trace: getting cacache info(C:\Users\<omited>\AppData\Local\Caches\xPacks, xpm:binaries:xpack-cmake-3.27.9-1-win32-x64.zip)...
Downloading https://github.com/xpack-dev-tools/cmake-xpack/releases/download/v3.27.9-1/xpack-cmake-3.27.9-1-win32-x64.zip...
trace: proxyUrl http://172.16.7.13:8080
trace: TypeError: HttpsProxyAgent is not a constructor
    at Xpack.cacheArchive (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/utils/xpack.js:483:30)
    at Xpack.downloadBinaries (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/utils/xpack.js:401:20)
    at async Install.pacoteExtractPackage (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:2077:7)
    at async Install.downloadAndProcessOneDependency (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1331:7)
    at async Promise.all (index 3)
    at async Install.downloadAndProcessDependencies (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1278:25)
    at async Install.installAllDependencies (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1115:7)
    at async Install.doRun (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:354:7)
    at async Xpm.main (D:\<omited>\magickwand.js\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:1046:20)
    at async Xpm.doStart (D:\<omited>\magickwand.js\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:282:22)
trace: CliError: HttpsProxyAgent is not a constructor in fetch https://github.com/xpack-dev-tools/cmake-xpack/releases/download/v3.27.9-1/xpack-cmake-3.27.9-1-win32-x64.zip
    at Xpack.cacheArchive (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/utils/xpack.js:491:15)
    at Xpack.downloadBinaries (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/utils/xpack.js:401:20)
    at async Install.pacoteExtractPackage (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:2077:7)
    at async Install.downloadAndProcessOneDependency (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1331:7)
    at async Promise.all (index 3)
    at async Install.downloadAndProcessDependencies (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1278:25)
    at async Install.installAllDependencies (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:1115:7)
    at async Install.doRun (file:///D:/<omited>/magickwand.js/node_modules/xpm/lib/xpm/install.js:354:7)
    at async Xpm.main (D:\<omited>\magickwand.js\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:1046:20)
    at async Xpm.doStart (D:\<omited>\magickwand.js\node_modules\xpm\node_modules\@ilg\cli-start-options\lib\cli-application.js:282:22) {
  exitCode: 2
}
HttpsProxyAgent is not a constructor in fetch https://github.com/xpack-dev-tools/cmake-xpack/releases/download/v3.27.9-1/xpack-cmake-3.27.9-1-win32-x64.zip
If you have an aggressive antivirus, try to reconfigure it, or temporarily disable it
error: download failed, quit
exit(3)
npm error code 3
npm error path D:\<omited>\magickwand.js
npm error command failed
npm error command C:\Program Files\git\bin\bash.exe -c xpm install --verbose --loglevel trace && xpm run npm-install
npm error A complete log of this run can be found in: C:\Users\<omited>\AppData\Local\npm-cache\_logs\2024-10-19T15_25_01_259Z-debug-0.log
```
## Context

- OS Name: Windows
- for Windows, the system version:  Microsoft Windows 10 Enterprise 10.0.19045

For http and https proxying, we use the same http server

## Comments

After Searching for an hour (unfortunately, I am not a JS expert) I think I found the issue
In lib/utils/xpack.js Line 39
https://github.com/xpack/xpm-js/blob/master/lib/utils/xpack.js#L39
```js
import HttpsProxyAgent from 'https-proxy-agent'
```
should be changed to:
```js
import { HttpsProxyAgent } from 'https-proxy-agent'
```

After hacking this into my node_modules copy of xpm, the whole installation just works

**Comment by ilg-ul** [comment]
Thank you for investigating. You are right, this is a bug, I'll fix it shortly.

**Comment by ilg-ul** [comment]
Please try `xpm@0.19.4` and let me know if it is ok.

Sorry for not being able to replicate the environment, I'm using neither Windows, nor proxies.

**Comment by Sonnenalle** [comment]
After replicating the issue, through removing the cache folders in local and roaming, I can confirm that the download now works with `xpm@0.19.4`
Thank you for this quick fix!
