### ISSUE TITLE
xpm link does not create parent folder

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#218]
```
> xpm link @xpack-dev-tools/xbb-helper
error: Error: ENOENT: no such file or directory, symlink '/Users/ilg/Library/xPacks/@xpack-dev-tools/xbb-helper/.link' -> '/Users/ilg/MyProjects/xpack-dev-tools.github/xpack-build-box.git/build-assets/xpacks/@xpack-dev-tools/xbb-helper'
    at async Object.symlink (node:internal/fs/promises:1000:10)
    at async Link.createLinkToRepoPackage (file:///Users/ilg/.nvm/versions/node/v20.18.0/lib/node_modules/xpm/lib/xpm/link.js:382:9)
    at async Link.doRun (file:///Users/ilg/.nvm/versions/node/v20.18.0/lib/node_modules/xpm/lib/xpm/link.js:150:7)
    at async Xpm.main (/Users/ilg/.nvm/versions/node/v20.18.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:1046:20)
    at async Xpm.doStart (/Users/ilg/.nvm/versions/node/v20.18.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:282:22)
    at async Xpm.start (/Users/ilg/.nvm/versions/node/v20.18.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:170:7)
error: running 'xpm link @xpack-dev-tools/xbb-helper' failed
```

The cause is the missing `/Users/ilg/MyProjects/xpack-dev-tools.github/xpack-build-box.git/build-assets/xpacks/@xpack-dev-tools/`.

**Comment by ilg-ul** [comment]
Fixed in 0.20.5 in 2024-12-10.
