### ISSUE TITLE
Installing large binaries fails on Windows 32-bit

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#61]
Large archives, like the RISC-V toolchain, fail:

```
trace: Install.doRun()
debug: os arch=ia32, platform=win32, release=10.0.19041
debug: node v12.14.0
xPack manager - install package(s)
trace: filePath: 'C:\Users\ilg\package.json'
trace: Install.installPackage('@xpack-dev-tools/riscv-none-embed-gcc@next')

Processing @xpack-dev-tools/riscv-none-embed-gcc@8.3.0-2.2.1...
trace: Install.installPackageGlobally('@xpack-dev-tools/riscv-none-embed-gcc@next')
Removing existing package from 'C:\Users\ilg\AppData\Roaming\xPacks\@xpack-dev-tools\riscv-none-embed-gcc\8.3.0-2.2.1'...
Installing globally in 'C:\Users\ilg\AppData\Roaming\xPacks\@xpack-dev-tools\riscv-none-embed-gcc\8.3.0-2.2.1'...
debug: npm @xpack-dev-tools/riscv-none-embed-gcc@next package extracted.
trace: expected integrity digest sha256-0INMNa4iEtUFHcXxR9kIgdSq5PJ+yFioQcTdZkmRdkE= for d0834c35ae2212d5051dc5f147d90881d4aae4f27ec858a841c4dd6649917641
trace: getting cacache info(C:\Users\ilg\AppData\Local\Caches\xPacks, xpm:binaries:xpack-riscv-none-embed-gcc-8.3.0-2.2-win32-x32.zip)...
trace: skip 1 levels
trace: rimraf C:\Users\ilg\AppData\Roaming\xPacks\@xpack-dev-tools\riscv-none-embed-gcc\8.3.0-2.2.1\.content
trace: ipath C:\Users\ilg\AppData\Local\Caches\xPacks\content-v2\sha512\81\8d\37882fa734df98cb19ad540218da5aaf394a9a678b3d410b01c5b47aa91c6bab9477fe74ae8b98797150fe9b24ae30390133eaf66aa4b499c120efd01743
Extracting 'xpack-riscv-none-embed-gcc-8.3.0-2.2-win32-x32.zip'...
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at createUnsafeBuffer (buffer.js:133:12)
    at allocate (buffer.js:394:10)
    at Function.allocUnsafe (buffer.js:359:10)
    at Function.concat (buffer.js:543:25)
    at PassThrough.stream.getBufferedValue (C:\Users\ilg\AppData\Roaming\npm\node_modules\xpm\node_modules\decompress-unzip\node_modules\get-stream\buffer-stream.js:46:26)
    at C:\Users\ilg\AppData\Roaming\npm\node_modules\xpm\node_modules\decompress-unzip\node_modules\get-stream\index.js:47:17
    at runMicrotasks (<anonymous>)
exit(2)
```

To make things worse, sometimes it passes. :-(

**Comment by ilg-ul** [comment]
Windows 32 is no longer supported; the problem does not occur on Arm 32.
