### ISSUE TITLE
xpm link asserts if the current package.json has no name/version

### ISSUE THREAD

**Issue by ilg-ul** [xpack/xpm-js#70]
If there is no name/version in `package.json`, instead of printing a civilised message, the `xpm link <package>` fails with messages like:

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(manifest.name)

    at new ManifestIds (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/lib/utils/xpack.js:369:7)
    at Link.doRun (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/lib/xpm/link.js:139:24)
    at async Xpm.main (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:1023:20)
    at async Function.doStart (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:277:22)
    at async Function.start (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:171:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(manifest.version)

    at new ManifestIds (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/lib/utils/xpack.js:370:7)
    at Link.doRun (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/lib/xpm/link.js:139:24)
    at async Xpm.main (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:1023:20)
    at async Function.doStart (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:277:22)
    at async Function.start (/Users/ilg/.nvm/versions/node/v12.14.0/lib/node_modules/xpm/node_modules/@ilg/cli-start-options/lib/cli-application.js:171:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by ilg-ul** [comment]
Fixed on 2021-01-24.
